In [1]:
import numpy as np
import torch 
import tensorflow as tf

Frobenius Norm
||X||f

In [2]:
X=np.array([[1,2],[3,4]])
# (1**2+2**2+3**2+4**2)**1/2

In [3]:
np.linalg.norm(X)

5.477225575051661

In [4]:
x_pt=torch.tensor([[1,2],[3,4.]])

In [5]:
torch.norm(x_pt)

tensor(5.4772)

In [6]:
x_tf=tf.Variable([[1,2],[3,4.]])
tf.norm(x_tf)

<tf.Tensor: shape=(), dtype=float32, numpy=5.477226>

Matrix multiplication

In [7]:
A=np.array([[3,4],[5,6],[7,8]])
B=np.array([1,2])

In [8]:
np.dot(A,B)

array([11, 17, 23])

In [9]:
A_pt=torch.tensor([[3,4],[5,6],[7,8]])
B_pt=torch.tensor([1,2])

In [10]:
torch.matmul(A_pt,B_pt)

tensor([11, 17, 23])

In [11]:
A_tf=tf.Variable([[3,4],[5,6],[7,8]])
B_tf=tf.Variable([1,2])

In [12]:
tf.linalg.matvec(A_tf,B_tf) 
# matvec for mat * vector

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([11, 17, 23])>

In [13]:
b_tf=tf.Variable([[1,3],[2,4]])
tf.linalg.matmul(A_tf,b_tf) 
# matmul for mat*mat

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[11, 25],
       [17, 39],
       [23, 53]])>

Numpy -> pytorch

In [14]:
b_pt=torch.from_numpy(B)
b_pt

tensor([1, 2], dtype=torch.int32)

Numpy -> tensorflow

In [15]:
a_tf=tf.convert_to_tensor(A,dtype=tf.int32)
a_tf

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[3, 4],
       [5, 6],
       [7, 8]])>

Symmetric Matrices

In [16]:
x_sym=np.array([[1,2,3],[2,4,5],[3,5,1]])
x_sym

array([[1, 2, 3],
       [2, 4, 5],
       [3, 5, 1]])

In [17]:
x_sym.T

array([[1, 2, 3],
       [2, 4, 5],
       [3, 5, 1]])

In [18]:
x_sym.T==x_sym

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

Identity Matrices

In [19]:
I=torch.tensor([[1,0,0],[0,1,0],[0,0,1]])
I

tensor([[1, 0, 0],
        [0, 1, 0],
        [0, 0, 1]])

A*I=A

In [20]:
A_pt

tensor([[3, 4],
        [5, 6],
        [7, 8]])

In [21]:
torch.matmul(I,A_pt)

tensor([[3, 4],
        [5, 6],
        [7, 8]])

Matrix inversion

In [22]:
X

array([[1, 2],
       [3, 4]])

In [24]:
Xinv=np.linalg.inv(X)
Xinv

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [26]:
torch.inverse(x_pt)

tensor([[-2.0000,  1.0000],
        [ 1.5000, -0.5000]])

In [27]:
tf.linalg.inv(x_tf)

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-2.0000002 ,  1.0000001 ],
       [ 1.5000001 , -0.50000006]], dtype=float32)>

In [29]:
# The inv of the follow mat is not possible
# XX=np.array([[-4,2],[-2,1]])
# XXinv=np.linalg.inv(XX)