In [15]:
import numpy as np
import torch
import matplotlib.pyplot as plt

Eigenvectors and EigenValue
Av=lambda v

In [16]:
A=np.array([[-1,4],[2,-2]])

In [17]:
lambdas,v=np.linalg.eig(A)
v

array([[ 0.86011126, -0.76454754],
       [ 0.51010647,  0.64456735]])

In [18]:
lambdas

array([ 1.37228132, -4.37228132])

Determinant

In [19]:
np.linalg.det(A)

-6.0

In [20]:
# If Det(A)=0, then A^-1 does not exist

In [21]:
A_PT=torch.tensor([[-1,4],[2,-2.]])
torch.det(A_PT)

tensor(-6.)

Eigrn-decomposition

In [22]:
v

array([[ 0.86011126, -0.76454754],
       [ 0.51010647,  0.64456735]])

In [23]:
vinv=np.linalg.inv(v)
vinv

array([[ 0.68251499,  0.80955878],
       [-0.54013799,  0.91074863]])

In [24]:
Lambda=np.diag(lambdas)
Lambda

array([[ 1.37228132,  0.        ],
       [ 0.        , -4.37228132]])

In [25]:
B=np.dot(v,np.dot(Lambda,vinv))
B

array([[-1.,  4.],
       [ 2., -2.]])

In [26]:
s=np.array([[1,2],[2,1]])

In [27]:
lambdas, Q=np.linalg.eig(s)

In [28]:
Lambda=np.diag(lambdas)

In [29]:
np.dot(Q,np.dot(Lambda,Q.T))

array([[1., 2.],
       [2., 1.]])

In [30]:
np.dot(Q,Q.T)

array([[ 1.00000000e+00, -2.23711432e-17],
       [-2.23711432e-17,  1.00000000e+00]])

array([ 3., -1.])

Singular value decomposition
    for non Square matrix 

In [33]:
A=np.array([[1,2],[2,3],[3,4]])

In [34]:
U,d,VT=np.linalg.svd(A)

In [35]:
U

array([[-0.33809817,  0.84795222,  0.40824829],
       [-0.55064932,  0.17354729, -0.81649658],
       [-0.76320047, -0.50085764,  0.40824829]])

In [36]:
d

array([6.54675564, 0.37415323])

In [37]:
VT

array([[-0.56959484, -0.82192562],
       [-0.82192562,  0.56959484]])

In [38]:
np.diag(d)

array([[6.54675564, 0.        ],
       [0.        , 0.37415323]])

In [40]:
D=np.concatenate((np.diag(d),[[0,0]]),axis=0)
D

array([[6.54675564, 0.        ],
       [0.        , 0.37415323],
       [0.        , 0.        ]])

In [41]:
np.dot(U,np.dot(D,VT))

array([[1., 2.],
       [2., 3.],
       [3., 4.]])

Pseudo-inversion(Moore-Penrose)
A^+

In [43]:
A
U
VT
d

array([6.54675564, 0.37415323])

In [48]:
D=np.diag(d)

In [50]:
Dinv=np.linalg.inv(D)
Dinv

array([[0.15274741, 0.        ],
       [0.        , 2.6727018 ]])

In [55]:
Dp=np.concatenate((Dinv,np.array([[0,0]]).T),axis=1)
Dp

array([[0.15274741, 0.        , 0.        ],
       [0.        , 2.6727018 , 0.        ]])

In [57]:
A_plus=np.dot(VT.T,np.dot(Dp,U.T))
A_plus

array([[-1.83333333, -0.33333333,  1.16666667],
       [ 1.33333333,  0.33333333, -0.66666667]])

In [59]:
np.linalg.pinv(A)

array([[-1.83333333, -0.33333333,  1.16666667],
       [ 1.33333333,  0.33333333, -0.66666667]])

In [66]:
A_PT=torch.tensor([[1,2],[2,3],[3,4.]])
torch.svd(A_PT)

torch.return_types.svd(
U=tensor([[-0.3381,  0.8480],
        [-0.5506,  0.1735],
        [-0.7632, -0.5009]]),
S=tensor([6.5468, 0.3742]),
V=tensor([[-0.5696, -0.8219],
        [-0.8219,  0.5696]]))

In [63]:
torch.pinverse(A_PT)

tensor([[0.3333, 0.6667],
        [0.3333, 0.1667]])

Trace operator

In [67]:
np.trace(A)

4

In [71]:
A_f=np.trace(np.dot(A,A.T))**.5
A_f
# Frobenius norm

6.557438524302