In [1]:
import numpy as np
import torch
import tensorflow as tf

Tensor transposition

In [2]:
X=np.array([[25,2],[5,26],[3,7]])
X

array([[25,  2],
       [ 5, 26],
       [ 3,  7]])

In [3]:
X.T

array([[25,  5,  3],
       [ 2, 26,  7]])

In [4]:
X_tf=tf.Variable([[25,2],[5,26],[3,7]])
X_pt=torch.tensor([[25,2],[5,26],[3,7]])

In [5]:
tf.transpose(X_tf)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[25,  5,  3],
       [ 2, 26,  7]])>

In [6]:
X_pt.T

tensor([[25,  5,  3],
        [ 2, 26,  7]])

Basic Tensor Arithematic

In [7]:
X*2

array([[50,  4],
       [10, 52],
       [ 6, 14]])

In [8]:
X+2

array([[27,  4],
       [ 7, 28],
       [ 5,  9]])

In [9]:
X_pt*2+2

tensor([[52,  6],
        [12, 54],
        [ 8, 16]])

In [10]:
torch.add(torch.mul(X_pt,2),2)

tensor([[52,  6],
        [12, 54],
        [ 8, 16]])

In [11]:
X_tf*2+2

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[52,  6],
       [12, 54],
       [ 8, 16]])>

In [12]:
A=X+2

In [13]:
A+X

array([[52,  6],
       [12, 54],
       [ 8, 16]])

In [15]:
A*X
# this is elementwise

array([[675,   8],
       [ 35, 728],
       [ 15,  63]])

Reduction

In [16]:
X.sum()

68

In [17]:
torch.sum(X_pt)

tensor(68)

In [18]:
tf.reduce_sum(X_tf)

<tf.Tensor: shape=(), dtype=int32, numpy=68>

In [19]:
X.sum(axis=0)

array([33, 35])

In [20]:
X.sum(axis=1)

array([27, 31, 10])

In [21]:
torch.sum(X_pt,0)

tensor([33, 35])

In [22]:
tf.reduce_sum(X_tf,0)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([33, 35])>

More such action(like summition) can be done
1. maximum
2. minimum
3. mean
4. product

The dot product

In [24]:
x=np.array([25,2,5])
y=np.array([0,1,2])

In [25]:
np.dot(x,y)

12

In [26]:
x_pt=torch.tensor([25,2,5])
y_pt=torch.tensor([0,1,2])

In [27]:
np.dot(x_pt,y_pt)

12

In [28]:
torch.dot(x_pt,y_pt)

tensor(12)

In [29]:
x_tf=tf.Variable([25,2,5])
y_tf=tf.Variable([0,1,2])

In [30]:
tf.reduce_sum(tf.multiply(x_tf,y_tf))

<tf.Tensor: shape=(), dtype=int32, numpy=12>

In [ ]:
3