# numpy library

In [108]:
import numpy as np

Dot product

In [109]:
A=np.array([1,2,3])
B=np.array([4,5,6])


In [110]:
type(A)

numpy.ndarray

In [111]:
np.dot(A,B)

32

Element wise Multiplication

In [112]:
X=A*B

Sum of all element

In [113]:
X.sum()

32

In [114]:
X.shape

(3,)

3D array

In [115]:
A=np.array([[[1,2,3],[2,3,4]],[[0,2,3],[3,2,0]]])
A

array([[[1, 2, 3],
        [2, 3, 4]],

       [[0, 2, 3],
        [3, 2, 0]]])

In [116]:
A.shape

(2, 2, 3)

In [117]:
A.dtype #data type of an Array

dtype('int32')

In [118]:
A=np.array([[1,2],[3,4]])
B=np.array([[1],[2]])
np.matmul(A,B) #For Matrix multiplication

array([[ 5],
       [11]])

In [119]:
# or
A @ B # a short cut for Mat-mul

array([[ 5],
       [11]])

In [120]:
#to import Data from any txt file 
A=np.genfromtxt('Data.txt',delimiter=',',skip_header=1)
A

array([[2., 3., 4.],
       [3., 4., 5.],
       [2., 3., 6.]])

In [121]:
A=np.concatenate((A,np.array([[3,2,3]])),axis=0) #to concatinate to add to outter [] write 0 then 1 and so on...
A 

array([[2., 3., 4.],
       [3., 4., 5.],
       [2., 3., 6.],
       [3., 2., 3.]])

In [122]:
# or
A=np.concatenate((A,np.array([[1],[2],[3],[4]])),axis=1)
A

array([[2., 3., 4., 1.],
       [3., 4., 5., 2.],
       [2., 3., 6., 3.],
       [3., 2., 3., 4.]])

In [123]:
np.savetxt('Data.txt',A,header="This is the newly changed file",footer="Thank you") #it will change the orignal file

Arithmetic operations and broadcasting

In [124]:
A=np.array([[1,2],[3,4]])
B=np.array([[4,3],[2,1]])
A+B

array([[5, 5],
       [5, 5]])

In [125]:
A+3 #Scalar additin

array([[4, 5],
       [6, 7]])

In [126]:
"""In broadcasting we can perform arithmetic operation 
on the array which donot have same dimension"""
B=np.array([1,2]) # B will be add as [[1,2],[1,2]]
A+B

array([[2, 4],
       [4, 6]])

In [127]:
"""//ERROR"""
# B=np.array([1,2,3])#here it is not possible since B cant be replicated to A
# A+B

'//ERROR'

Comparision oprators

In [128]:
A=np.array([[1,2],[3,4]])
B=np.array([[4,3],[2,1]])
A!=B

array([[ True,  True],
       [ True,  True]])

Array indexing

In [129]:
A=np.array([[[1,2,3],[2,3,4]],[[0,2,3],[3,2,0]]])
A.shape

(2, 2, 3)

In [130]:
A

array([[[1, 2, 3],
        [2, 3, 4]],

       [[0, 2, 3],
        [3, 2, 0]]])

In [131]:
A[1,1,1] # outer, to , inner []

2

In [132]:
A[1] # it is a sub array

array([[0, 2, 3],
       [3, 2, 0]])

In [133]:
A[0:1,0:2,0:3]

array([[[1, 2, 3],
        [2, 3, 4]]])

In [134]:
A[1,1,:]

array([3, 2, 0])

In [135]:
A[1,0]

array([0, 2, 3])

In [136]:
np.zeros((5,3))#for null array

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [137]:
np.eye(3)#for an Identity matrix of dim 3*3

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [138]:
np.random.rand(5) # for random vector

array([0.44191226, 0.23866736, 0.72043601, 0.0512841 , 0.68808786])

In [139]:
np.random.randn(2,3)#for random no near to 0

array([[-0.58536225,  1.93228768, -0.3911724 ],
       [ 1.5707939 , -0.13774982,  0.90317305]])

In [140]:
np.full((2,3),41) # for fixed value

array([[41, 41, 41],
       [41, 41, 41]])

In [141]:
np.arange(10,90,3) # for range from 10 to 90 with a diff of 3

array([10, 13, 16, 19, 22, 25, 28, 31, 34, 37, 40, 43, 46, 49, 52, 55, 58,
       61, 64, 67, 70, 73, 76, 79, 82, 85, 88])

In [142]:
np.arange(10,90,3).reshape(3,3,3) # to re-shape it in the dim 3,3,3 

array([[[10, 13, 16],
        [19, 22, 25],
        [28, 31, 34]],

       [[37, 40, 43],
        [46, 49, 52],
        [55, 58, 61]],

       [[64, 67, 70],
        [73, 76, 79],
        [82, 85, 88]]])

In [143]:
np.arange(10,90,3).reshape(3,9,-1) #it will automatically calculate the value of one

array([[[10],
        [13],
        [16],
        [19],
        [22],
        [25],
        [28],
        [31],
        [34]],

       [[37],
        [40],
        [43],
        [46],
        [49],
        [52],
        [55],
        [58],
        [61]],

       [[64],
        [67],
        [70],
        [73],
        [76],
        [79],
        [82],
        [85],
        [88]]])

In [144]:
np.linspace(0,10,20) # for equally spaced no from,to,no of numbers

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])